Rewrite RCON unit to use standard library
opensoldat/opensoldat pull request #68
Opened 2021-08-31 17:31 UTC by helloer

- RCON server now uses standard library unit (ssockets) for socket handling
- Removed Indy10 dependency as described in #2 
- Added token bucket rate limiting for new connections

This change needs proper testing on Windows(and maybe macOS) before merging.

2021-09-01 13:49 UTC, BranDougherty commented on server/Rcon.pas
> -  {$ENDIF}
Looks like we lost `OnAdminDisconnect`, probably easy to add it back.

2021-09-01 14:18 UTC, helloer commented on server/Rcon.pas
> -  {$ENDIF}
Fixed in 7cac05a

2021-09-02 16:18 UTC, BranDougherty requested changes

2021-09-02 16:18 UTC, BranDougherty commented on server/Rcon.pas
> +  Data.IOTimeout := 5000;
This is not sufficient for a 5 second timeout, a client can just send data without newlines and keep the thread alive forever. For example this python client should still disconnect after 5 seconds:

```python
import socket
import time

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((socket.gethostname(), 23073))

while True:
    s.sendall(b'data without newlines')
    time.sleep(1)
```

Maybe something along the lines of:
```pascal
// Init
ConnectTime := GetTickCount64;
Timeout := ConnectTime + 5000;

// Loop
if not FAuthed then
begin
  CurrentTime := GetTickCount64;

  if CurrentTime > Timeout then
    // Timeout...

  Data.IOTimeout := 5000 - (CurrentTime - ConnectTime);
end;
```

2021-09-03 01:00 UTC, BranDougherty commented on server/Rcon.pas
> +  end;
I haven't investigated this yet but it seems like it doesn't actually shut down every thread.

2021-09-03 01:00 UTC, BranDougherty commented on server/Rcon.pas
> +            MainConsole.Console('[RCON] Admin connected (' + FData.RemoteAddress.GetIPString + ').', GAME_MESSAGE_COLOR);
Pretty sure this is not thread safe. You could just pass that string to the message queue, because that gets printed to the console anyways. It might also be possible to make the server version of `TConsole.Console` thread safe, seems like its doing a lot of unnecessary stuff.

2021-09-03 01:00 UTC, BranDougherty commented on server/Rcon.pas
> +    MainConsole.Console('[RCON] Admin disconnected (' + FData.RemoteAddress.GetIPString + ').', GAME_MESSAGE_COLOR);
See above `TConsole.Console` comment.

2021-09-09 17:34 UTC, helloer commented on server/Rcon.pas
> +  Data.IOTimeout := 5000;
Good catch, this should be fixed in a14417a.

2021-09-09 17:46 UTC, helloer commented on server/Rcon.pas
> +            MainConsole.Console('[RCON] Admin connected (' + FData.RemoteAddress.GetIPString + ').', GAME_MESSAGE_COLOR);
Yeah, it's not thread safe (neither is old implementation). Making TConsole thread-safe would be a much better solution, but that needs to be done in another PR.

2021-09-10 00:29 UTC, BranDougherty commented on server/Rcon.pas
> +  Data.IOTimeout := 5000;
The connections can still be kept alive longer than 5s but a14417a looks fine to me.

2021-09-14 21:23 UTC, BranDougherty submitted a review, later dismissed

2021-09-25 19:07 UTC, BranDougherty approved these changes
Thanks! Seriously nice to not be relying on Indy10 anymore, and one more thing off the 1.8 checklist.

2021-09-25 19:11 UTC, merged