feature: copy chat contents to clipboard
opensoldat/opensoldat pull request #72
Opened 2021-09-28 15:15 UTC by episage

This feature adds CTRL+C functionality when a chat is open. It copies chat content to the clipboard.

With this feature people can actually share interesting links or messages between each other.

2021-09-29 10:30 UTC, helloer commented
`ChatText` only stores your own chat input, so this feature doesn't actually copy "chat contents" i.e. other player messages. It might be more practical to copy:
a) Last inserted message from `MainConsole`
b) Everything from `MainConsole`
c) Selected message (but I'm not sure what's the best approach for implementing selection would be)

2021-09-29 10:53 UTC, episage commented
No problem. I implemented b). Please take a look.

2021-09-30 14:35 UTC, episage commented
Any comments?

2021-09-30 14:35 UTC, episage commented
Does this look good enough to be merged?

2021-09-30 17:15 UTC, BranDougherty commented
Hi, thanks for recognizing the problem and making a PR. This is obviously better than having no option to copy from the chat, so I'm interested in merging (although long term I think the UX needs more than this). I pushed a few fixes and I'll take a deeper look at this in a few days. I'd like to have a slightly better understanding of what FPC and SDL2 are doing here. I'm vaguely aware that clipboards have some kind of mimetype, and SDL2 is probably assigning a mimetype of UTF-8. I *think* `WideString`s are internally using UTF-16, and I'm interested in the details of how that conversion is happening.

2021-10-01 10:56 UTC, episage commented
I'm thinking that there should be a message "Chat copied to clipboard" popping up somewhere

2021-10-01 15:19 UTC, XvayS commented
I have some concerns about the use of `Ctrl+C` as a shortcut for this action (copy everything from `MainConsole`), because there could be a conflict in the future with extending ChatInput's functionality when it will have a selectable text feature and therefore it would need a way to copy the selected text too. And the most convenient and natural shortcut for this will be the same `Ctrl+C` (and `Ctrl+Ins`) combination.
That's why I'd suggest to use some other keyboard shortcut for copying the context of the whole console "screen".

2021-10-02 06:46 UTC, furai commented
So how this thing works? What does it actually copy? Is it required or just nice to have? If it might clash then maybe let's rethink it's purpose/implementation? What about clicking on messages when chat is expanded instead of using keyboard?

2021-10-02 15:54 UTC, BranDougherty commented
It copies every message on the screen with chat expanded when you press `Ctrl+C`. It's very bare-bones, I was just thinking of it as a temporary feature where we would get some basic copying functionality going. I would have no problem changing the controls or removing it when we have something better. A mouse control makes sense, when I first saw this PR I started implementing that, but then I thought about various UI features that I would like to have in order to implement it properly and I decided to just get this merged and figure out everything I would want in the console later. That's still the plan, but if people are opposed to it I don't have to merge.

Its really not hard to imagine a better chat experience. Remembering more messages, scrolling, and clicking messages to copy them could be a good start.

2021-10-06 17:03 UTC, episage commented
How to move this forward?

2021-10-07 08:39 UTC, helloer requested changes

2021-10-07 08:39 UTC, helloer commented on shared/Console.pas
> +    Result := Result + TextMessage[I] + LineEnding;
```
Console.pas(152,15) Warning: (4104) Implicit string type conversion from "AnsiString" to "WideString"
Console.pas(152,39) Warning: (4105) Implicit string type conversion with potential data loss from "WideString" to "AnsiString"
```
Return type should be `WideString`

2021-10-07 08:39 UTC, helloer commented on shared/Console.pas
> +    function GetContentsAsPlainText():AnsiString;
Missing space after `():`

2021-10-07 08:39 UTC, helloer commented on shared/Console.pas
> +function TConsole.GetContentsAsPlainText():AnsiString;
Missing space after `():`

2021-10-07 08:39 UTC, helloer commented on client/ControlGame.pas
> +      SDL_SetClipboardText(PChar(BigConsole.GetContentsAsPlainText));
WideString needs to be casted to UTF8String first
 `SDL_SetClipboardText(PChar(UTF8String(BigConsole.GetContentsAsPlainText)));`

2021-10-07 14:19 UTC, episage commented
Many thanks for the review. I made the necessary changes.

Also, @helloer , does UTF8 work in Soldat? I tried to use korean but the chat console prints square boxes.

2021-10-07 17:54 UTC, BranDougherty approved these changes
LGTM. I'm getting some slightly odd behavior when I set `SDL_VIDEODRIVER=wayland` on Linux but I think its a result of SDL2 bugs and I feel no need to hold this up any longer for that.

2021-10-07 17:54 UTC, merged

2021-10-07 18:07 UTC, BranDougherty commented
Graphically speaking Soldat is a ways off from supporting unicode. It does no font enumeration/fallback, which is why you get the boxes (AKA "tofu") when you try to render any characters not in that font. It pretty much does no Complex Text Layout (CTL).